urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

from mezzanine.core.views import direct_to_template

from django.http import HttpResponse
admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = patterns("",                       
    (r'^location_field/', include('location_field.urls')),
    (r'^expeditions/', include('expeditions.urls')),
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),

     (r'^jsi18n/$', 'django.views.i18n.javascript_catalog'),

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", 'utils.views.browse_dir', {"template": "index.html", "media_path" : "frontpage/"}, name="home"),
    url("^utils/", include('utils.urls')),
    url("^user_profiles/", include('user_profiles.urls')),
    url(r'', include('social_auth.urls')),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part. Make
    # sure to uncheck "show in navigation" when you create the page,
    # since the link to the homepage is always hard-coded into all the
    # page menus that display navigation on the site. Also note that
    # the normal rule of adding a custom template per page with the
    # template name using the page's slug doesn't apply here, since
    # we can't have a template called "/.html" - so for this case, the
    # template "pages/index.html" can be used.

    # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    (r'^i18n/setlang/$', 'django.views.i18n.set_language'),
    ("^", include("mezzanine.urls")),    
    #(r'^i18n/', include('django.conf.urls.i18n')),    
    
    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

    
)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler500 = "mezzanine.core.views.server_error"

resume/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from mezzanine.pages.models import Page

from mezzanine.core.fields import RichTextField
from transmeta import TransMeta
try:
    from _pyio import __metaclass__
except:
    __metaclass__ = type
from transmeta_pages.meta import MetaPageTranslate
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

class Resume(models.Model):
    name = models.CharField(max_length=255)
    date_column_name = models.CharField(max_length=255,default=u"Name")
    description_column_name = models.CharField(max_length=255,default=u"Description")
    picture_column_name = models.CharField(max_length=255,default=u"Snapshot")
    
    def __unicode__(self):
        return unicode(self.name)
    
class Experience(models.Model):
    __metaclass__ = TransMeta    
    description = RichTextField(verbose_name="description")            
        
    date = models.DateField(null=True,blank=True)
    picture = models.ImageField(null=True,blank=True,upload_to="uploads")
    picture_reasonable = ImageSpecField(image_field='picture',
                                       processors=[ResizeToFill(700, 500)],
                                       format='PNG')
    picture_thumbnail = ImageSpecField(image_field='picture',
                                       processors=[ResizeToFill(250, 200)],
                                       format='PNG')
    resume = models.ForeignKey(Resume)
    
    class Meta:
        translate = ('description', )
        ordering = ('date',)
        
    def __unicode__(self):
        return unicode(self.date)

class Link(models.Model):
    __metaclass__ = TransMeta
    
    title = models.CharField(max_length=255,verbose_name="title")
    href = models.CharField(max_length=255) 
    experience = models.ForeignKey(Experience)
    
    class Meta:
        translate = ('title', )
        
    def __unicode__(self):
        return unicode(self.title)


class PageWithResume(Page):
    __metaclass__ = MetaPageTranslate
    
    content = RichTextField(verbose_name="content")
    resume = models.ForeignKey(Resume)
    
    class Meta:
        translate = ('content', )

resume/views.py
# Create your views here.

resume/templates/pages/pagewithresume.html
{% overextends "pages/page.html" %}
{% load mezzanine_tags %}

{% block extra_head %}
<LINK href="{{ STATIC_URL }}css/modal_config.css" rel="stylesheet" type="text/css">
<LINK href="{{ STATIC_URL }}css/expedition_list.css" rel="stylesheet" type="text/css">
<script data-main="{{STATIC_URL}}js/main/default.js" src="{{STATIC_URL}}js/libs/require/require.js"></script>
{% block extra_extra_head %}
{% endblock %}
{% endblock %}

{% block main %}

{{ page.pagewithresume.content|richtext_filter|safe }}

{% block experience_list %}	
	<table class="table table-bordered">
     <caption></caption>
		<thead>
			<tr>
				<th>{{page.pagewithresume.resume.date_column_name}}</th>
				<th>{{page.pagewithresume.resume.description_column_name}}</th>
				<th>{{page.pagewithresume.resume.picture_column_name}}</th>
			</tr>
		</thead>
		<tbody>		
			{% for experience in page.pagewithresume.resume.experience_set.all %}
				<tr>
					<td>{{experience.date}}</td>
					<td {% if not experience.picture %}colspan="2"{%endif%}>
							<div class="upper-container">
							{{experience.description|richtext_filter|safe}}
							</div>
							{% if experience.link_set.all|length %}
							<div class="lower-container">
								<div class="row-fluid">
									{% for link in experience.link_set.all %}
									<div class="span4">
									<a href="{{link.href}}" >{{link.title}}</a>
									</div>
									{% endfor %}
								</div>
							</div>						
							{% endif %}
					</td>
					{% if experience.picture %}
					<td>												
						<a href="#exp{{experience.id}}" role="button" data-toggle="modal"><img class="experience-picture" src="{{experience.picture_thumbnail.url}}" width="150px" /></a>
						<div id="exp{{experience.id}}" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" width="100%">
						<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3>{{experience.title}}</h3>
						</div>
						<div class="modal-body">
							<a href="{{experience.picture.url}}" target="_blank">
								<img src="{{experience.picture_reasonable.url}}" />
							</a>
						</div>
						<div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>				
						</div>
						</div>						
					</td>
					{% endif %}
				</tr>
				
			{% endfor %}			
		</tbody>
    </table>

{% block modal_dialogs %}
{% endblock %}
{% endblock %}

{% endblock %}